void leNome(void);
void limparBufferEntrada(void);
int validarNum(char*);
//char leCpf(char);
//char leCnpj(char);
//char leCodBarras(char);
//char leData(char);
//char leCel(char);
void leSenha(char*);